### PR TITLE
Add link to elixirscript-brunch

### PR DESCRIPTION
**Pull request by knewter**
Adds a link to a Brunch plugin that provides ElixirScript module
support.

### CODE REVIEW

**Comment by bryanjos** [comment]
Awesome! Thanks for making that. Can't wait to try it out

**Comment by knewter** [comment]
It's not 100% sensible yet, because it makes the __lib outputs in the app
directory and it should really just not.  But I didn't know a good way to
fix it.  Bare brunch project + this plugin, add an app/foo.ex module, it's
in your app and require'able. :)

On Thu, Aug 27, 2015 at 8:40 AM, Bryan Joseph <notifications@github.com>
wrote:

> Awesome! Thanks for making that. Can't wait to try it out
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bryanjos/elixirscript/pull/78#issuecomment-135433777>.
>



-- 
*Josh Adams*
CTO | isotope|eleven <http://www.isotope11.com>
[cell] (205) 215-3957
[work] (877) 476-8671 x201

[mail]
3800 Colonnade Pkwy
Suite 140
Birmingham, AL 35242

**Comment by bryanjos** [comment]
Good to know it's that easy! I'll try it out on a phoenix project.

As for the file output and compilation, I would love any ideas on how to make it better. This is my first time doing a project like this so any feedback or advice would definitely be helpful

**Comment by knewter** [comment]
I thought about it some and I didn't have a good answer for this yet, or
I'd have mentioned it.  I was just happy to get it working (accidentally
published 2 versions of the package that weren't yet working because I had
some false positives due to my experimentation ahead of time)

On Thu, Aug 27, 2015 at 9:11 AM, Bryan Joseph <notifications@github.com>
wrote:

> Good to know it's that easy! I'll try it out on a phoenix project.
>
> As for the file output and compilation, I would love any ideas on how to
> make it better. This is my first time doing a project like this so any
> feedback or advice would definitely be helpful
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bryanjos/elixirscript/pull/78#issuecomment-135446728>.
>



-- 
*Josh Adams*
CTO | isotope|eleven <http://www.isotope11.com>
[cell] (205) 215-3957
[work] (877) 476-8671 x201

[mail]
3800 Colonnade Pkwy
Suite 140
Birmingham, AL 35242

**Comment by railcar88** [comment]
@knewter do you mind exposing a phoenix dummy app that is properly configured to use the elixirscript-brunch plugin? That way it is crystal clear where things need to go and what the configs need to look like. If you already have one that is properly set up can you point me to it?

**Pull request merged**
